name: LavaEscape
version: ${project.version}
main: com.sirhiggelbottom.lavaescape.plugin.LavaEscapePlugin
api-version: 1.13
author:  Sirhiggelbottom
description: A competitive and environmental survival Minecraft game where players escape rising lava.

commands:
  lavaEscape:
    description: Opens the main menu
    usage: /<command>
    aliases: [lava menu, lava]

permissions:
  lavaescape.admin:
    description: Allows access to all LavaEscape commands
    default: op
  lavaescape.play:
    description: Allows joining and playing LavaEscape games
    default: true
  lavaescape.create:
    description: Allows creating new LavaEscape arenas
    default: op
  lavaescape.modify:
    description: Allows modifying LavaEscape game settings
    default: op

